# Generated by Django 4.1.1 on 2023-03-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_register_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='user_name',
            new_name='username',
        ),
    ]
