# Generated by Django 4.1.1 on 2023-03-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('new', models.BooleanField(default=False)),
                ('manafacture', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('catagory', models.CharField(editable=False, max_length=50)),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
    ]
