# Generated by Django 4.1.1 on 2023-03-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_catagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
