# Generated by Django 4.1.1 on 2023-03-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
