# Generated by Django 4.1.1 on 2023-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_product_img2_product_img3_product_img4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
