# Generated by Django 4.1.1 on 2023-03-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_product_img2_alter_product_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(max_length=100),
        ),
    ]
